version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - REACT_APP_API_URL=http://server:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev --host

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    command: npm run start:dev

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata: