version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - REACT_APP_API_URL=http://server:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

  server:
    env_file:
      - "./.env"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV={NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://{DB_USER}:{DB_PASSWORD}@db:{DB_PORT}/{DB_NAME}
    command: npm run start:dev
    depends_on:
      - db

  db:
    env_file:
      - "./.env"
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB={DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  uploads: