services:
  db:
    build: ./db
    container_name: ig-clone-db
    environment:
      POSTGRES_DB: ig_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ig-clone-network

  server:
    build:
      context: ./server
      target: production
    container_name: ig-clone-server
    env_file:
      - .env
    environment:
      - PORT=3000
    depends_on:
      - db
    networks:
      - ig-clone-network

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /api/v1 # Relative URL - proxied by nginx
        VITE_GOOGLE_CLIENT_ID: 504692938992-3h533nn2o1878b5a83lcrgjkujvuo27n.apps.googleusercontent.com
        VITE_GOOGLE_AUTH_URL: /auth/google # Relative URL - proxied by nginx
    container_name: ig-clone-client
    ports:
      - "80:80" # Changed to port 80 for production
    depends_on:
      - server
    networks:
      - ig-clone-network

volumes:
  postgres_data:

networks:
  ig-clone-network:
    driver: bridge
